apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: example-4
spec:
  template:
    spec:
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["t"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: Gt
          values: ["1"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["2"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["ap-northeast-2a", "ap-northeast-2c"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: example-4
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: example-4
spec:
  role: "karpenter-project-hama"
  amiSelectorTerms:
    - alias: al2@latest
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "project-hama"
  securityGroupSelectorTerms:
    - tags:
        aws:eks:cluster-name: "project-hama"