apiVersion: apps/v1
kind: Deployment
metadata:
  name: example3-inflate
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example3-inflate
  template:
    metadata:
      labels:
        app: example3-inflate
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
          resources:
            requests:
              cpu: "1"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "256Mi"