apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: example5
spec:
  template:
    spec:
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot"]
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["t"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: example-5
      expireAfter: 1m # node lifetime
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized # WhenEmptyOrUnderutilized or WhenEmpty
    consolidateAfter: 2m
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: example-5
spec:
  role: "karpenter-project-hama"
  amiSelectorTerms:
    - alias: al2@latest
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "project-hama"
  securityGroupSelectorTerms:
    - tags:
        aws:eks:cluster-name: "project-hama"
  tags:
    env: eks-from-terraform